# Travis CI configuration for setproctitle
#
# Wheel building branch.

services:
  - docker

matrix:
  include:
    - env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        - PLAT=manylinux1_x86_64
      sudo: required

    - env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
        - PLAT=manylinux1_i686
        - PRE_CMD=linux32
      sudo: required

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/tools/build-wheels.sh
  - ls wheelhouse/
